config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
        devise_for :users
        get :thank, controller: :feedbacks
        get :search, controller: :welcome
        get :autocomplete, controller: :welcome
        get '/rule' => 'pages#rule'
        get '/our_team' => 'pages#our_team'
        get '/contact' => 'pages#contact'
        get '/about' => 'pages#about'
        resources :books, only: [:index,:show]
        # resources :users, only: [:index,:show]
        resources :feedbacks, only: [:new,:create]
        resources :authors, only: [:index, :show]
        resources :genres, only: [:index, :show]
        resources :locations, only:[:index, :show]
        get 'welcome/index'
        
        root 'welcome#index'
        # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
        namespace :admin do
          get :new_author_at_book, controller: :authors
          get :new_genre_at_book, controller: :genres  
          resources :feedbacks, except: [:new,  :create]
          resources :books, except: [:index,:show]
          resources :authors, except: [:index, :show]
          resources :genres, except: [:index,:show]
          resources :users#, except: [:index, :show]
          resources :locations, except: [:index,:show]
          resources :statistic, only: :index          
        end  
  end    
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, :description, presence: true                    
  mount_uploader :image, ImageUploader

  belongs_to :user, class_name: "User", foreign_key: 'user_id'
  belongs_to :holder, class_name: "User", foreign_key: 'holder_id', optional: true


  belongs_to :author
  belongs_to :genre
  belongs_to :location

  
  after_save :count_of_held_books2#, :is_available
  before_save :is_available
  before_update :is_available

  
  def count_of_held_books2
  	users = User.all
  		users.each do |user|
  			user.held = Book.where(holder_id: user.id.to_i).count
        user.added = Book.where(user_id:user.id.to_i).count
  			user.save
  		end
  end    
  def is_available
     if self.holder_id.nil?
        self.available = true
        #self.save
     else 
        self.available = false
        #self.save
     end
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::AdminController
  # before_action :authenticate_user!, except: [:index,:show]
  before_action :set_book, only: [:edit, :update, :destroy]

  # before_action :check_admin 
=begin 
  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end
=end
  # GET /books/new
  def new
    @book = Book.new
  # @author = Author.new
  end

  # GET /books/1/edit
  def edit
    #@author = Author.new
  
  end

  # POST /books
  # POST /books.json

  
  def create
    # render plain: params[:book].inspect
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
        
                
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :language, :description, :user_id, :author_id, :genre_id, :location_id, :rating,:balance,:holder_id, :image, :available)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # before_action :authenticate_user!, except: [:index,:show]
  before_action :set_book, only: :show#, :edit, :update, :destroy]
 
  
  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end
=begin
  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
 #       increase_added(@book)
user = User.find_by(id: @book.user_id)
user.added = user.added.to_i + 1
user.save
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
        
                
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
=end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :language, :description, :user_id, :author_id, :genre_id, :location_id, :rating,:balance,:holder_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/admin/books/_form.html.erb
<%= form_with(model: [:admin, book], html:{multipart: true}, remote: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
<!-- <div class= "form-group"> -->
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :book_title, placeholder: "Title of the book" , class: "form-control line_select" %>
  </div>
  <div class="form-group add_file_style">
    <%#= form.label :image %>
     <%#= form.file_field :image, id: :book_image %> 
  </div>

  <div class="form-group">
   <%= form.file_field :image, id: :book_image, 'data-placeholder':t('book.no_file'),'data-buttonBefore':"true",'data-text':t('book.add_image'),'data-btnClass':"btn-primary", class: "filestyle" %>  
   <!-- +"No file" -->
   <!-- +"Add image" -->
   <!-- <input type="file" class="filestyle" data-btnClass="btn-primary"> -->
  </div>
  
  <div class="form-group">
    <%= form.label :language %>
    <%= form.select(:language, [['русский'], ['английский']],{}, {:class => 'form-control line_select'})%>   
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :book_description, placeholder: t('book.brief_description'), class: "form-control" %>
    <!-- "Book's brief description" -->
  </div>

  <div class="form-group">
    <%= form.label :user_id %>
    <p class="text-muted">
      <%= t('book.please_select_who_brought_this_book') %>
      <!-- Please select the user who brought the book -->
    </p>
    <%= form.collection_select(:user_id, User.all, :id, :name_with_initial ,{}, class: 'form-control line_select') %>
    <%#= form.collection_select(:user_id, User.all, :id, :name) %>
  </div>



  <div class="form-group">
    <%#= form.label :author_id %>
    <%#= form.select(:author_id, Author.all.collect {|p| [ p.name+" "+p.surname, p.id ] } + [ ['add new author', 'new']],{},{:onchange => "newAuthor();", class: "form-control line_select"}) %>    
  </div>



  <div class="form-group" >
        <%= form.label :author_id %>
        <div id="author_area">
            <%= form.select(:author_id, Author.all.collect {|p| [ p.name+" "+p.surname, p.id]} + [ [t('book.add_new_author'), 'new']],{:selected =>Author.last.id.to_i}, {:onchange => "newAuthor();", id: 'author_select', class: "form-control line_select", data: {remote: true, url: url_for( action: 'new_author_at_book', controller: '/admin/authors')}}) %>  
            <!-- 'add new author' -->
        </div>
  </div>


  <div class="form-group">
    <%= form.label :genre_id %>
    <div id="genre_area">
        <%= form.select(:genre_id, Genre.all.collect {|p| [ p.genre_name, p.id ] } + [ [t('book.add_new_genre'), 'new']],{:selected =>Genre.last.id.to_i},{:onchange => "newGenre();", id: 'genre_select', id: 'genre_select', class: 'form-control line_select', data: {remote: true, url: url_for( action: 'new_genre_at_book', controller: '/admin/genres')}}) %>  
        <!-- 'add new genre' -->
    </div>
    
    <%#= form.collection_select(:genre_id, Genre.all, :id, :genre_name) %>
  </div>



  <div class="form-group">
    <%= form.label :location_id %>
    <%#= form.collection_select(:location_id, Location.all, :id, :name) %>
    <%= form.select(:location_id, Location.all.collect {|p| [ p.name, p.id ] } + [ [t('book.add_new_location'), 'new']],{},{:onchange => "newLocation();",class:'form-control line_select'}) %>
    <!-- 'add new location' -->
  </div>
  <!-- <div class="field"> -->
    <%#= form.label :rating %>
    <%#= form.text_field :rating, id: :book_rating %>
  <!-- </div> -->
  <div class="form-group">

    <%= form.label :holder_id %>
    <p class="text-muted">
      <%= t('book.this_field_indicates') %>
      <!-- This field indicates the user who took the book from the location. If the book in the location now, select: -->
      <b> 
       <%= t('book.no_holder') %>
        <!-- no holder -->
      </b>
    </p>
    <%= form.collection_select(:holder_id, User.all, :id, :name_with_initial, {include_blank:  t('book.no_holder') }, {:class=>"form-control line_select"}) %>
    <%#= form.collection_select(:user_id, User.all, :id, :name) %>
    <!-- 'no holder' -->
  </div>
  <div class="actions">
    <%= form.submit t('.submit', action: @book.new_record? ? t('common.add') : t('common.change')), class:'btn btn-primary'%>
    <%= link_to t('common.back'), :back, class:'btn btn-secondary'%>
    <!-- 'Back' -->
  </div>
<% end %>
<%#= render "admin/authors/form" %>



<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add new </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="rendering_of_form_author">      	
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
      <div class="modal-footer">
        
        
      </div>
    </div>
  </div>
</div>

app/views/admin/books/edit.html.erb
<h1>
		<!-- Editing Book -->
		<%= t('admin.book.edit.editing_book') %>
</h1>

<%= render 'form', book: @book %>
<%= link_to t('book.destroy_book'), admin_book_path(@book), method: :delete, data: { confirm: t('action.are_you_sure') }, class: "btn btn-danger" %>
<%#= link_to 'Delete', @book %> 
<%#= link_to 'Back', :back %>
<!-- 'Destroy book' -->
<!-- 'Are you sure?' -->

app/views/admin/books/new.html.erb
<h1 class="text_in_one_row">
	<%= t('admin.book.new.new_book') %>	
</h1>		
<%= render 'form', book: @book %>