config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
        devise_for :users
        get :thank, controller: :feedbacks
        get :search, controller: :welcome
        get :autocomplete, controller: :welcome
        get '/rule' => 'pages#rule'
        get '/our_team' => 'pages#our_team'
        get '/contact' => 'pages#contact'
        get '/about' => 'pages#about'
        resources :books, only: [:index,:show]
        # resources :users, only: [:index,:show]
        resources :feedbacks, only: [:new,:create]
        resources :authors, only: [:index, :show]
        resources :genres, only: [:index, :show]
        resources :locations, only:[:index, :show]
        get 'welcome/index'
        
        root 'welcome#index'
        # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
        namespace :admin do
          get :new_author_at_book, controller: :authors
          get :new_genre_at_book, controller: :genres  
          resources :feedbacks, except: [:new,  :create]
          resources :books, except: [:index,:show]
          resources :authors, except: [:index, :show]
          resources :genres, except: [:index,:show]
          resources :users#, except: [:index, :show]
          resources :locations, except: [:index,:show]
          resources :statistic, only: :index          
        end  
  end    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
   # before_action :force_json, only: :search
  before_action :authenticate_user!, except: [:index,:show,:search,:autocomplete]
  def index
  	@books = Book.order("created_at desc").limit(5)
    @locations = Location.all
  end

  def search
          # byebug          
          @authors = Author.ransack(surname_cont: params[:q]).result(distinct: true)
          @books = Book.ransack(title_cont: params[:q]).result(distinct: true)
          @locations = Location.ransack(name_cont: params[:q]).result(distinct: true)
          @genres = Genre.ransack(genre_name_cont: params[:q]).result(distinct: true)

        if user_signed_in?&&current_user.admin?  
            @users = User.ransack(email_cont: params[:q]).result(distinct: true)
        end

 	  respond_to do |format|
    
 		   format.html{}
 		   format.json {}
 	  end
  end
  def autocomplete
          # byebug          
          @authors = Author.ransack(surname_cont: params[:q]).result(distinct: true).limit(5)
          @books = Book.ransack(title_cont: params[:q]).result(distinct: true).limit(5)
          @locations = Location.ransack(name_cont: params[:q]).result(distinct: true).limit(5)
          @genres = Genre.ransack(genre_name_cont: params[:q]).result(distinct: true).limit(5)

        if user_signed_in?&&current_user.admin?  
            @users = User.ransack(email_cont: params[:q]).result(distinct: true).limit(5)
        end

    respond_to do |format|
    
       format.html{}
       format.json {}
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<!-- <h1>Bookboard</h1> -->
<!-- <p>Find desired books</p> -->
<section class="container nav justify-content-center font_nav">
      <% if user_signed_in? %>
        <span><%= link_to t('welcome.books'), books_path, class: "nav-item nav-link" %></span>
     <% end %>
     <span><%= link_to t('welcome.authors'), authors_path, class: "nav-item nav-link" %></span>
     <span><%= link_to t('welcome.genres'), genres_path, class: "nav-item nav-link" %></span>
     <span><%= link_to t('welcome.locations'), locations_path, class: "nav-item nav-link" %></span>
     <% if user_signed_in?&&current_user.admin? %>
           <span><%= link_to t('welcome.users'), admin_users_path, class: "nav-item nav-link" %></span>
    <% end %>
</section>
<center>
    <h1><%= t('welcome.recent') %></h1>
</center>
<div class="card-deck d-flex flex-nowrap">
	   <% @books.each do |book| %>
      	<div class= "card parrent_bottom">
            <% if book.image? %>
              <%=  link_to (image_tag book.image, class: "card-img-top"), book_path(book) %>
            <% else %>
              <%= image_tag("no-image.png") %>
            <% end %>
      		 <!--  <%=  link_to (image_tag book.image, class: "card-img-top"), book_path(book) if book.image? %><br> -->
            <!-- else image_tag("no-image.png")  -->
            <div class="align_bottom">
                <div class="card-body text-center">
                    <h5 class="card-title">
                        <%= link_to book.title, book_path(book) %>
                    </h5>
                  <% if book.available? %>
                      <%#= "(available now) " %>
                      <div>
                          <span class="badge badge-success"><%= t('common.available') %></span>
                          <!-- available now -->
                      </div>

                  <%else %>
                      <%#= "(busy now)" %>
                      <div>
                          <span class="badge badge-secondary"><%= t('common.busy') %></span>
                          <!-- busy now -->
                      </div>

                  <% end %>
                  <p class="card-text">
                    <%= t('welcome.brought') %>
                     <%= l book.created_at, :format=> :short %>

                    <!-- <%= " "+book.created_at.strftime("%e %B")+t('welcome.to') %>  -->
                    <%= link_to book.location.name , location_path(book.location)%>
                  </p>
          </div>
            </div>

      	</div>
      	<!-- <hr> -->
	   <% end %>
</div>
<br>

<!--
<% @locations.each do |location| %>
      <%= image_tag location.picture.url(:large) if location.picture? %>
<% end %>
 -->


<center>
  <h1>
    <!-- Our locations -->
    <%= t('welcome.our_locations') %>
  </h1>
</center>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">

  <div class="carousel-inner">
    <% @locations.each do |location| %>
        <% if location.id==1 and location.picture? %>
          <div class="carousel-item active">
                <%= link_to (image_tag location.picture.url, alt: location.name, class: "d-block w-100"), location_path(location)  if location.picture? %>
                <!-- <img class="d-block w-100" src="..." alt="First slide"> -->
          </div>
        <% else if location.picture? %>
                <div class="carousel-item">
                    <!-- <img class="d-block w-100" src="..." alt="Third slide"> -->
                    <%= link_to (image_tag location.picture.url, alt: location.name, class: "d-block w-100"), location_path(location)  if location.picture? %>
                </div>
                <% else %>
                  <% next %>
                <% end %>
        <% end %>

    <%end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/welcome/search.html.erb
<% if params[:q].present? %>
	<h1>
		<%= t('search.search_results_for') %> "<%= params[:q] %>" 
		<!-- Search Results for -->
	</h1> 
<% else %>
 	<h1>
 		<%= t('search.please_type_something') %>
 		<!-- "Please, type anything" -->
 	 </h1>
<% end %>

<div>
	<% if @books.present? %> 
	 	<h2>
	 	<!-- Books: -->
	 	<%= t('welcome.books') %>:
	 	</h2>
	<% end %>
	<% @books.each do |book| %>
		<%= link_to book.title, book_path(book) %>
	<% end %>	

</div>
<div><% if @authors.present? %>
		<h2>
			<!-- Authors: -->
			<%= t('welcome.authors') %>:
		</h2>
	<% end %>
	<% @authors.each do |author| %>
		<%= link_to	author.name+" "+author.surname, author_path(author) %>
	<% end %>
</div>
<div>
	<% if @genres.present? %>
	<h2>
		<!-- Genres: -->
		<%= t('welcome.genres') %>:
	</h2>
	<% end %>
	<% @genres.each do |genre| %>
		<%=	link_to genre.genre_name, genre_path(genre) %>
	<% end %>
</div>

<div>
	<% if @locations.present? %>
	<h2>
		<!-- Locations: -->
		<%= t('welcome.locations') %>:
	</h2>
	<% end %>
	<% @locations.each do |location| %>
		<%= link_to	location.name, location_path(location) %>
	<% end %>
</div>
<% if user_signed_in?&&current_user.admin? %>
	<div>
		<% if @users.present? %>
			<h2>
				<!-- Users: -->
				<%= t('welcome.users') %>:
			</h2>
		<% end %>
		<% @users.each do |user| %>
			<%= link_to	user.email, admin_user_path(user) %>
		<% end %>
	</div>
<% end %>
<%= link_to t('common.back'), :back, class: 'btn btn-secondary' %>