config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
        devise_for :users
        get :thank, controller: :feedbacks
        get :search, controller: :welcome
        get :autocomplete, controller: :welcome
        get '/rule' => 'pages#rule'
        get '/our_team' => 'pages#our_team'
        get '/contact' => 'pages#contact'
        get '/about' => 'pages#about'
        resources :books, only: [:index,:show]
        # resources :users, only: [:index,:show]
        resources :feedbacks, only: [:new,:create]
        resources :authors, only: [:index, :show]
        resources :genres, only: [:index, :show]
        resources :locations, only:[:index, :show]
        get 'welcome/index'
        
        root 'welcome#index'
        # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
        namespace :admin do
          get :new_author_at_book, controller: :authors
          get :new_genre_at_book, controller: :genres  
          resources :feedbacks, except: [:new,  :create]
          resources :books, except: [:index,:show]
          resources :authors, except: [:index, :show]
          resources :genres, except: [:index,:show]
          resources :users#, except: [:index, :show]
          resources :locations, except: [:index,:show]
          resources :statistic, only: :index          
        end  
  end    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable

    attr_accessor :password_confirmation
  	# attr_protected :password
  	 # validates_confirmation_of :password
  	 # validates_confirmation_of :password, :password_confirmation, :on => :create
  	validates :password, :password_confirmation, presence: true, on: :create

	has_many :added_books, :class_name => 'Book', :foreign_key => 'user_id'
	has_many :held_books, :class_name => 'Book', :foreign_key => 'holder_id'

	has_many :locations, :through => :books
	has_many :authors, :through => :books
	has_many :genres, :through => :books

	before_update :calculate_balance
  before_save :you_admin

	def calculate_balance
		self.balance = added.to_i - held.to_i
	end
  def you_admin
    if self.id.to_i == 1
      self.admin = true
    end
  end

	def name_with_initial
		 unless name.nil?
    	"#{name} #{surname} #{email}"
    	 else
    	 "#{email}"
    	 end
  	end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  # before_action :authenticate_user!#, except: [:index,:show]
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :check_admin, on: [:show,:edit], unless: :own_page?

    def own_page?
      # puts "hello"

      if user_signed_in? and current_user.id == params[:id].to_i
        true
      end
    end
  # before_action :authenticate_user!, except: :new
  # GET /users
  # GET /users.json

  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if params[:user][:password].blank?&&params[:user][:password_confirmation].blank?
              params[:user].delete :password
              params[:user].delete :password_confirmation
       end
    respond_to do |format|


      if @user.update(user_params)
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :surname, :phone, :email, :balance, :added, :held,:password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!#, except: [:index,:show]
  before_action :set_user, only: :show
  # before_action :check_admin
  # GET /users
  # GET /users.json
  def index

    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end
=begin
  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
=end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
     # @user = User.find_by id: params[:id]
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :surname, :phone, :email, :balance, :added, :held)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/Untitled Folder/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

    <%= link_to 'New User', new_user_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Phone</th>
      <th>e-mail</th>
      <th>Balance</th>
      <th>Added</th>
      <th>Held</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.surname %></td>
        <td><%= user.phone %></td>
        <td><%= user.email %></td>
        <td><%= user.balance %></td>
        <td><%= user.added %></td>
        <td><%= user.held %></td>
        <td><%= link_to 'Show', user %></td>
        
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Back', root_path %>

app/views/admin/users/Untitled Folder/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @user.surname %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @user.balance %>
</p>
<p>
  <strong><%= @user.name %> added</strong>
  <%= @user.added %> books
</p>
<p>
	Added by <%= @user.name %>:<br>
	<% @user.books.each do |book| %>
		
		|<%= link_to book.title, book_path(book) %>|  
	<% end %> 
</p>
<p>
	Hold by <%= @user.name %>:<br>
	<% @holder.books.each do |book| %>
		
	<%#= link_to book.title, book_path(book) %>|
	<% end %> 
</p>

<%= link_to 'Edit profile', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>