config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
        devise_for :users
        get :thank, controller: :feedbacks
        get :search, controller: :welcome
        get :autocomplete, controller: :welcome
        get '/rule' => 'pages#rule'
        get '/our_team' => 'pages#our_team'
        get '/contact' => 'pages#contact'
        get '/about' => 'pages#about'
        resources :books, only: [:index,:show]
        # resources :users, only: [:index,:show]
        resources :feedbacks, only: [:new,:create]
        resources :authors, only: [:index, :show]
        resources :genres, only: [:index, :show]
        resources :locations, only:[:index, :show]
        get 'welcome/index'
        
        root 'welcome#index'
        # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
        namespace :admin do
          get :new_author_at_book, controller: :authors
          get :new_genre_at_book, controller: :genres  
          resources :feedbacks, except: [:new,  :create]
          resources :books, except: [:index,:show]
          resources :authors, except: [:index, :show]
          resources :genres, except: [:index,:show]
          resources :users#, except: [:index, :show]
          resources :locations, except: [:index,:show]
          resources :statistic, only: :index          
        end  
  end    
end

app/models/feedback.rb
class Feedback < ApplicationRecord
	validates :title, :text, presence: true                    
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
end

app/controllers/admin/feedbacks_controller.rb
class Admin::FeedbacksController < Admin::AdminController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json

  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end
=begin
  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end
=end
  # GET /feedbacks/1/edit
  def edit
  end
=begin
  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end
=end
  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to admin_feedback_url(@feedback), notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to admin_feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:email, :title, :text)
    end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  # before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
=begin  
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end
=end
  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
=begin 
  def edit
  end
=end
  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to thank_path, notice: 'Feedback was successfully created.' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end
  def thank
  end
=begin
  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
=end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:email,:title, :text)
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_with(model: @feedback, local: true) do |form| %>
  <% if feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feedback.errors.count, "error") %> <%= t('activerecord.errors.prohibited_this_feedback') %></h2>
       <!-- from being saved: -->
       <!-- feedback -->
       <!-- prohibited this -->
      <ul>
      <% feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, id: :feedback_email , placeholder: t('session.enter_email'), class: "form-control" %>
    <!-- title -->
  </div>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :feedback_title , placeholder: t('activerecord.attributes.feedback.title'), class: "form-control" %>
    <!-- title -->
  </div>

  <div class="form-group">
    <%= form.label :text %>
    <%= form.text_area :text, id: :feedback_text, placeholder: t('feedback.whats_your_opinion_about'), class: "form-control" %>
    <!-- 'Your feedback enter here' -->
  </div>
  
  
  <div class="actions">
    <%= form.submit t('action.send'), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/feedbacks/new.html.erb
<h1 class="text_in_one_row">
		<!-- New Feedback -->
		<%= t('feedback.your_feedback') %>
</h1>

<%= render 'form', feedback: @feedback %>

<%= link_to t('common.back'), admin_feedbacks_path, class: 'btn btn-secondary' %>
<!-- 'Back' -->

app/views/feedbacks/thank.html.erb
<h1>
	<!-- Thank for your feedback -->
	<%= t('feedback.thank_feedback') %>
</h1>
<h2>
<!-- Wee will connect as soon as possible -->
	<%= t('feedback.we_ll_connect_as') %>
</h2>